### ISSUE TITLE
Is it possible to make the custom data dir a runtime value?

### ISSUE THREAD

**Issue by lud** [mathieuprog/tz#11]
Currently it is set at compile time.

Would that be ok for the value to be fetched at runtime, so it can be set as an environment variable in production environments or docker containers?

Thank you

**Comment by mathieuprog** [comment]
I actually have no experience with builds. What about `config/runtime.exs`?

**Comment by lud** [comment]
That won't work because your have the following code directly in the module body:

```elixir
@custom_data_dir Application.get_env(:tz, :data_dir)
```

So it is evaluated when the library is compiled, not when runtime is launched.

**Comment by mathieuprog** [comment]
What about changing that line to

```elixir
defp custom_data_dir() do
  Application.get_env(:tz, :data_dir)
end
```

**Comment by lud** [comment]
Yep sure, that would work.

**Comment by mathieuprog** [comment]
Can you try it out and check if your deployments work with different config? And send a PR? 
Or are you certain this will just do?

**Comment by lud** [comment]
Sorry we switched to tzdata when we faced that problem, I have currently no app using tz.

**Comment by mathieuprog** [comment]
This has been added in version 0.21.1.

Note that tzdata has [bugs](https://elixirforum.com/t/29358), sometimes may return wrong times or raise errors. That's why I created this library in the first place, I would never have spent months writing it otherwise.

Only `tz` and `time_zone_info` output correct times.

**Comment by lud** [comment]
Hi,

Yes I know but we needed to configure the custom dir at runtime to work well with our docker deployment. That was for CRON-like jobs, just dealing with 2022+ dates.

I'll try again tz on a future iteration but I honestly don't know when I will work on this project again.
