### ISSUE TITLE
Logger.warn/1 is deprecated on Elixir 1.15 in favour of Logger.warning/2

### ISSUE THREAD

**Issue by kipcole9** [mathieuprog/tz#19]
With the publishing of [Elixir 1.15.0-rc.0](https://github.com/elixir-lang/elixir/releases/tag/v1.15.0-rc.0) today, the following deprecation is now in effect:
```elixir
==> tz
Compiling 16 files (.ex)
warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  lib/tz/watch_periodically.ex:19: Tz.WatchPeriodically.watch/1
```
Given `Logger.warn/1` is a macro perhaps there's a way to conditionally compile in either `Logger.warning/2` if its defined and `Logger.warn/1` if not?  I'm fine to work on a PR if that's helpful.

**Comment by mathieuprog** [comment]
Hello Kip! Sure a PR would be helpful

**Comment by mathieuprog** [comment]
Thank you @kipcole9 that was very helpful!
