### ISSUE TITLE
2024b data file causes parsing error

### ISSUE THREAD

**Issue by bernardd** [mathieuprog/tz#28]
The 2024b data file contains one month specified as `April` rather than `Apr`. This causes the following error during compilation:

```elixir
= Compilation error in file lib/tz/compiler_runner.ex ==
** (ArithmeticError) bad argument in arithmetic expression
    lib/tz/iana_file_parser.ex:402: Tz.IanaFileParser.month_string_to_integer/1
    lib/tz/iana_file_parser.ex:162: Tz.IanaFileParser.transform_rule/1
    lib/tz/iana_file_parser.ex:57: Tz.IanaFileParser.parse_strings_into_maps/2
    lib/tz/iana_file_parser.ex:71: Tz.IanaFileParser.parse_strings_into_maps/2
    lib/tz/iana_file_parser.ex:18: Tz.IanaFileParser.parse/1
    lib/tz/compiler.ex:21: anonymous fn/2 in Tz.Compiler.compile/0
    (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
```

While the full month name is not used anywhere else, [this post](https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/Y5KABB56LLOPHQJL4MFHWHSLR7KJ2XSP/) says that it's valid nonetheless (albeit with some fixes to make sure it's not used again).

**Comment by mathieuprog** [comment]
Fixed

**Comment by bernardd** [comment]
Thanks heaps!

**Comment by linusdm** [comment]
Just for future reference: as of IANA time zone database 2024b, version `0.27.2` of tz is required to avoid the mentioned parsing error. So for applications using the [automatic time zone database updates](https://hexdocs.pm/tz/readme.html#automatic-time-zone-data-updates) feature, this will require updating the tz version.

Thanks for the quick fix!
