### ISSUE TITLE
Out of memory when recompiling time zone periods on a memory-limited system

### ISSUE THREAD

**Issue by OldhamMade** [mathieuprog/tz#9]
I'm running an app on fly.io, with a 1GB container size. Using Tzdata I can boot without issue. However, switching to Tz I'm seeing this on startup:

```text
14:18:01.356 [info] Tz is downloading the latest IANA time zone database (version 2021c)...
14:18:02.785 [info] Tz download done
14:18:02.814 [info] Tz is recompiling time zone periods...
[    7.749887] Out of memory: Killed process 511 (beam.smp) total-vm:2665752kB, anon-rss:902056kB, file-rss:0kB, shmem-rss:63628kB, UID:0 pgtables:2380kB oom_score_adj:0
Main child exited with signal (with signal 'SIGKILL', core dumped? false)
Reaped child process with pid: 595, exit code: 0
Starting clean up.
Process appears to have been OOM killed!
```

Config is:

```elixir
config :elixir, :time_zone_database, Tz.TimeZoneDatabase
config :tz, reject_time_zone_periods_before_year: 2019
```

I'm not able to replicate this locally, unfortunately. I'm using `docker run --memory 512m --rm -i -p 8080:8080 {container}` but I'm on macOS and don't hit a memory error.

**Comment by OldhamMade** [comment]
BTW, I don't see this as a "bug" as such. I think it's simply a consequence of the implementation, and is perfectly valid. Saying that, it does mean that anyone using memory-restricted containers would struggle to add and use Tz, which may harm adoption.

**Comment by mathieuprog** [comment]
Could you also confirm that Tzdata updates successfully to 2021c (from 2020e I think) in fly.io?

**Comment by OldhamMade** [comment]
I'm going to close this issue. I managed to work around it by adding a 5gb swap space to my VM as it boots, which works around the memory limitation. This allows Tz to build successfully.

**Comment by mathieuprog** [comment]
Thank you for the feedback.

I think those with memory-limited system should update the IANA tzdata files manually.

We could make it consume less memory, but would it then really be reliable for systems with tight memory limits anyway?
So I would say this work is not worth it.

I also have personally no real understanding of the significance of the amount of memory that tz needs on a server in production, with its possible impacts.
